openapi: 3.0.0
info:
  title: Adoption Request Status API
  version: "1.0"
paths:
  /adoption-requests/{id}:
    patch:
      summary: Update status of an adoption request
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum:
                    - approved
                    - rejected
      responses:
        '200':
          description: Updated adoption request object
        '400':
          description: Invalid status
        '404':
          description: Request not found
